### ISSUE TITLE
Plugin installation failed: Connection closed

### ISSUE THREAD

**Issue by ksketo** [kartoza/docker-qgis-desktop#21]
I am not able to install python plugins. I get either a connection timeout or connection closed error.

I am using version 2.14 and the status for plugin repositories is 'connected'.

Edit:
 How can I at least install a plugin manually if not possible through the GUI?

**Comment by timlinux** [comment]
Can you share how you are running QGIS in docker? (please paste the command line used to launch it)

**Comment by ksketo** [comment]
That's my docker-compose.yml:

```
db:
  image: kartoza/postgis:9.4-2.1
  environment:
    - USERNAME=docker
    - PASS=docker

qgisdesktop:
  image: kartoza/qgis-desktop:2.14
  hostname: qgis-server
  volumes:
    # Wherever you want to mount your data from
    - ./gis:/root/gis
    - ./qgis_sample_data:/root/qgis_sample_data
    # Unix socket for X11
    - /tmp/.X11-unix:/tmp/.X11-unix
  links:
    - db:db
  ports:
    - 8888:8888
  environment:
    - DISPLAY=192.168.200.28:0
  command: /usr/bin/qgis
```

I am running it on Mac os x btw.
