### ISSUE TITLE
QGIS 2.18 wont start

### ISSUE THREAD

**Issue by Inkimar** [kartoza/docker-qgis-desktop#40]
Hi!

Wanting to run the 2.18 version.

This is my docker-compose

```
db:
  image: kartoza/postgis:9.4-2.1
  environment:
    - USERNAME=docker
    - PASS=docker
  
qgisdesktop:
  image: kartoza/qgis-desktop:2.18
  hostname: qgis-server
  volumes:
    # Wherever you want to mount your data from
    - ./gis:/gis
    # Unix socket for X11
    - /tmp/.X11-unix:/tmp/.X11-unix
  links:
    - db:db
  environment: 
    - DISPLAY=unix:1
  command: /usr/bin/qgis
```

Getting this error from the qgisdesktop

```
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsMessageLog::logMessage(QString const&, QString const&, QgsMessageLog::MessageLevel)+0x100)[0x7f6f80709660]
qgisdesktop_1  | /usr/bin/qgis[0x40c029]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(qt_message_output(QtMsgType, char const*)+0x2f)[0x7f6f7fd89e9f]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x15543c)[0x7f6f7fe6f43c]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(QFile::open(QFlags<QIODevice::OpenModeFlag>)+0xcd)[0x7f6f7fe24b4d]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::logMessageToFile(QString const&)+0x72)[0x7f6f806c72b2]
qgisdesktop_1  | Warning: QFile::at: Cannot set file position 0 
qgisdesktop_1  | Stacktrace (piped through c++filt):
qgisdesktop_1  | /usr/bin/qgis[0x40bbb2]
qgisdesktop_1  | /usr/bin/qgis[0x40bff2]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(qt_message_output(QtMsgType, char const*)+0x2f)[0x7f6f7fd89e9f]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x15543c)[0x7f6f7fe6f43c]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(QFile::open(QFlags<QIODevice::OpenModeFlag>)+0xcd)[0x7f6f7fe24b4d]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::logMessageToFile(QString const&)+0x72)[0x7f6f806c72b2]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::debug(QString const&, int, char const*, char const*, int)+0x418)[0x7f6f806c7768]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsMessageLog::logMessage(QString const&, QString const&, QgsMessageLog::MessageLevel)+0x100)[0x7f6f80709660]
qgisdesktop_1  | /usr/bin/qgis[0x40c029]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(qt_message_output(QtMsgType, char const*)+0x2f)[0x7f6f7fd89e9f]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x15543c)[0x7f6f7fe6f43c]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(QFile::open(QFlags<QIODevice::OpenModeFlag>)+0xcd)[0x7f6f7fe24b4d]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::logMessageToFile(QString const&)+0x72)[0x7f6f806c72b2]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::debug(QString const&, int, char const*, char const*, int)+0x418)[0x7f6f806c7768]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsMessageLog::logMessage(QString const&, QString const&, QgsMessageLog::MessageLevel)+0x100)[0x7f6f80709660]
qgisdesktop_1  | /usr/bin/qgis[0x40c029]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(qt_message_output(QtMsgType, char const*)+0x2f)[0x7f6f7fd89e9f]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(+0x15543c)[0x7f6f7fe6f43c]
qgisdesktop_1  | /usr/lib/x86_64-linux-gnu/libQtCore.so.4(QFile::open(QFlags<QIODevice::OpenModeFlag>)+0xcd)[0x7f6f7fe24b4d]
qgisdesktop_1  | /usr/lib/libqgis_core.so.2.18.20(QgsLogger::logMessageToFile(QString const&)+0x72)[0x7f6f806c72b2]
kartoza_qgisdesktop_1 exited with code 13
```
